<?php
/**
 * Plain-text alert emails on storm transitions, in the WC Antifraud style.
 *
 * @package Bot_Storm_Radar
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class BSR_Email_Alerts {

	/**
	 * @param array $ctx from, to, at, minute, score, explanation, metrics.
	 * @return bool
	 */
	public static function send_transition( array $ctx ) {
		$addresses = BSR_Helpers::sanitize_email_list( BSR_Helpers::opt( 'email_recipients', '' ) );
		if ( empty( $addresses ) ) {
			return false;
		}
		$site  = get_bloginfo( 'name' );
		$to    = (string) $ctx['to'];
		$from  = (string) $ctx['from'];
		$m     = is_array( $ctx['metrics'] ?? null ) ? $ctx['metrics'] : [];
		$when  = wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), (int) $ctx['at'] );
		$radar = admin_url( 'admin.php?page=bot-storm-radar' );

		$titles = [
			'warning' => __( 'Bot storm warning', 'bot-storm-radar' ),
			'storm'   => __( 'Bot storm detected', 'bot-storm-radar' ),
			'cooling' => __( 'Bot storm cooling down', 'bot-storm-radar' ),
			'calm'    => __( 'Bot storm over', 'bot-storm-radar' ),
		];
		$subject = sprintf( '[%s — Bot Storm Radar] %s', $site, $titles[ $to ] ?? $to );

		$body   = [];
		if ( ! empty( $ctx['started_from'] ) ) {
			$body[] = sprintf( __( 'Bot Storm Radar moved from %1$s through %2$s to %3$s at %4$s, all within one minute.', 'bot-storm-radar' ), strtoupper( (string) $ctx['started_from'] ), strtoupper( $from ), strtoupper( $to ), $when );
		} else {
			$body[] = sprintf( __( 'Bot Storm Radar moved from %1$s to %2$s at %3$s.', 'bot-storm-radar' ), strtoupper( $from ), strtoupper( $to ), $when );
		}
		$body[] = __( 'Radar-only release: nothing was blocked, challenged or rate-limited.', 'bot-storm-radar' );
		$body[] = '';
		$body[] = __( 'WHY:', 'bot-storm-radar' );
		$body[] = (string) ( $ctx['explanation'] ?? '' );
		$body[] = '';
		$body[] = __( 'LAST MINUTE:', 'bot-storm-radar' );
		$body[] = sprintf( 'Storm score: %s', $ctx['score'] ?? '-' );
		$body[] = sprintf( 'Requests: %d, distinct addresses: %d, single-hit addresses: %d', (int) ( $m['total'] ?? 0 ), (int) ( $m['ips'] ?? 0 ), (int) ( $m['single'] ?? 0 ) );
		$body[] = sprintf( 'HTML-serving addresses: %d, beacon addresses: %d', (int) ( $m['html_ips'] ?? 0 ), (int) ( $m['beacon_ips'] ?? 0 ) );
		$body[] = sprintf( 'Distinct user agents: %d, networks: %d', (int) ( $m['uas'] ?? 0 ), (int) ( $m['nets'] ?? 0 ) );
		$body[] = sprintf( '5xx responses: %d, slow responses: %d', (int) ( $m['err5'] ?? 0 ), (int) ( $m['slow'] ?? 0 ) );
		if ( ! empty( $m['top_class'] ) ) {
			$body[] = sprintf( 'Busiest sensitive endpoint class: %s (%s of requests)', $m['top_class'], self::pct( $m['concentration'] ?? 0 ) );
		}
		if ( ! empty( $m['classes'] ) && is_array( $m['classes'] ) ) {
			arsort( $m['classes'] );
			$parts = [];
			foreach ( array_slice( $m['classes'], 0, 6, true ) as $c => $n ) {
				if ( $n > 0 ) {
					$parts[] = $c . ' ' . (int) $n;
				}
			}
			if ( $parts ) {
				$body[] = 'Classes: ' . implode( ', ', $parts );
			}
		}
		$body[] = '';
		$body[] = __( 'ACTIONS:', 'bot-storm-radar' );
		$body[] = sprintf( 'Radar: %s', $radar );
		$body[] = sprintf( 'Counter backend: %s', BSR_Counters::backend_label() );
		$body[] = '';
		$body[] = '---';
		$body[] = sprintf( __( 'Generated by Bot Storm Radar %1$s on %2$s', 'bot-storm-radar' ), BSR_VERSION, $site );

		$headers = [
			'Content-Type: text/plain; charset=UTF-8',
			sprintf( 'From: %s <%s>', $site, get_option( 'admin_email' ) ),
		];

		$sent = true;
		foreach ( $addresses as $addr ) {
			if ( ! wp_mail( $addr, $subject, implode( "\n", $body ), $headers ) ) {
				$sent = false;
			}
		}
		return $sent;
	}

	/**
	 * @param float $v
	 * @return string
	 */
	private static function pct( $v ) {
		return round( (float) $v * 100 ) . '%';
	}
}
